# Generated by Django 5.2.1 on 2026-07-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_inventory_and_stocktake'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcategory',
            name='class_type',
            field=models.CharField(choices=[('IT', 'IT资产'), ('ADMIN', '行政资产')], db_index=True, default='IT', max_length=12, verbose_name='资产大类'),
        ),
    ]
