# Generated by Django 5.2.1 on 2026-07-27 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


ALL_SCOPES = ["assets", "inventory", "stocktake", "reports", "settings"]


def configure_existing_managers(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(app_label, model_name)
    AssetManagerRole = apps.get_model("assets", "AssetManagerRole")

    for user in User.objects.filter(is_staff=True):
        AssetManagerRole.objects.update_or_create(
            user=user,
            defaults={"scopes": ALL_SCOPES},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_assetcategory_class_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetManagerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scopes', models.JSONField(blank=True, default=list, verbose_name='可管理板块')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asset_manager_role', to=settings.AUTH_USER_MODEL, verbose_name='管理员')),
            ],
            options={
                'verbose_name': '资产管理员权限',
                'verbose_name_plural': '资产管理员权限',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='AssetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[('assign', '领用'), ('loan', '借用')], max_length=12, verbose_name='申请类型')),
                ('requested_name', models.CharField(db_index=True, max_length=120, verbose_name='设备名称')),
                ('reason', models.CharField(blank=True, max_length=500, verbose_name='用途说明')),
                ('expected_return_at', models.DateField(blank=True, null=True, verbose_name='预计归还')),
                ('status', models.CharField(choices=[('pending', '待分配'), ('fulfilled', '已分配'), ('rejected', '已驳回'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=16, verbose_name='状态')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('manager_notes', models.CharField(blank=True, max_length=500, verbose_name='处理说明')),
                ('assigned_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulfilled_requests', to='assets.asset', verbose_name='已分配资产')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_asset_requests', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '资产领用借用申请',
                'verbose_name_plural': '资产领用借用申请',
                'ordering': ['status', '-created_at'],
                'indexes': [models.Index(fields=['requester', 'status'], name='asset_req_user_status_idx'), models.Index(fields=['requested_name', 'status'], name='asset_req_name_status_idx')],
            },
        ),
        migrations.RunPython(configure_existing_managers, migrations.RunPython.noop),
    ]
