# Generated by Django 5.2.1 on 2026-07-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_normalize_asset_display_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='brand',
            field=models.CharField(blank=True, max_length=80, verbose_name='品牌'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='model_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='型号'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='单价'),
        ),
    ]
