# Generated by Django 5.2.1 on 2026-07-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_inventoryitem_brand_inventoryitem_model_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='purchase_channel',
            field=models.CharField(blank=True, choices=[('supplier', '合作供应商'), ('ecommerce', '电商'), ('other', '其他')], default='', max_length=20, verbose_name='采购途径'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='minimum_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='保障数量'),
        ),
    ]
