# Generated by Django 5.2.1 on 2026-07-28 01:57

from django.db import migrations, models


def seed_statuses_and_normalize_assets(apps, schema_editor):
    Asset = apps.get_model('assets', 'Asset')
    AssetStatus = apps.get_model('assets', 'AssetStatus')
    defaults = [
        ('available', '在库', 10),
        ('loaned', '借用中', 20),
        ('assigned', '使用中', 30),
        ('disposed', '报废', 40),
    ]
    for code, name, sort_order in defaults:
        AssetStatus.objects.update_or_create(
            code=code,
            defaults={
                'name': name,
                'sort_order': sort_order,
                'is_system': True,
                'is_active': True,
            },
        )

    legacy_map = {
        'pending': 'available',
        'available': 'available',
        'inspection': 'available',
        'transfer': 'available',
        'repair': 'available',
        'assigned': 'assigned',
        'loaned': 'loaned',
        'lost': 'disposed',
        'retired': 'disposed',
        'disposed': 'disposed',
    }
    for asset in Asset.objects.all().iterator():
        changed = []
        normalized = legacy_map.get(asset.status)
        if normalized and normalized != asset.status:
            asset.status = normalized
            changed.append('status')
        elif not normalized:
            AssetStatus.objects.get_or_create(
                code=asset.status,
                defaults={
                    'name': asset.status,
                    'sort_order': 100,
                    'is_system': False,
                    'is_active': True,
                },
            )
        custom_data = dict(asset.custom_data or {})
        if 'responsible_person' in custom_data:
            custom_data.pop('responsible_person', None)
            asset.custom_data = custom_data
            changed.append('custom_data')
        if changed:
            asset.save(update_fields=changed)


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_inventoryitem_purchase_channel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='状态编码')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='状态名称')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='排序')),
                ('is_system', models.BooleanField(default=False, verbose_name='系统状态')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '资产状态',
                'verbose_name_plural': '资产状态',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(db_index=True, default='available', max_length=32, verbose_name='状态'),
        ),
        migrations.RunPython(
            seed_statuses_and_normalize_assets,
            migrations.RunPython.noop,
        ),
    ]
