# Generated by Django 5.2.1 on 2026-07-28 03:00

import django.db.models.deletion
from django.db import migrations, models


def classify_existing_assets_as_it(apps, schema_editor):
    AssetCategory = apps.get_model("assets", "AssetCategory")
    AssetCategory.objects.all().update(class_type="IT")


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_alter_asset_assigned_to_alter_asset_wired_mac_and_more'),
    ]

    operations = [
        migrations.RunPython(classify_existing_assets_as_it, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='assetcategory',
            options={'ordering': ['code'], 'verbose_name': '资产类型', 'verbose_name_plural': '资产类型'},
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetcategory', verbose_name='资产类型'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='class_type',
            field=models.CharField(choices=[('IT', 'IT资产'), ('ADMIN', '行政资产')], db_index=True, default='IT', max_length=12, verbose_name='资产分类'),
        ),
        migrations.AlterField(
            model_name='assetnumbersequence',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='assets.assetcategory', verbose_name='资产类型'),
        ),
    ]
