# Generated by Django 5.2.1 on 2026-07-28 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_alter_assetcategory_options_alter_asset_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_key', models.CharField(max_length=255, unique=True, verbose_name='事件标识')),
                ('event_type', models.CharField(db_index=True, max_length=48, verbose_name='通知类型')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='收件邮箱')),
                ('subject', models.CharField(max_length=255, verbose_name='邮件主题')),
                ('body', models.TextField(verbose_name='邮件正文')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('processing', '发送中'), ('sent', '已发送'), ('failed', '发送失败')], db_index=True, default='pending', max_length=16, verbose_name='发送状态')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='尝试次数')),
                ('last_error', models.TextField(blank=True, verbose_name='最后错误')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_notifications', to=settings.AUTH_USER_MODEL, verbose_name='收件人账号')),
            ],
            options={
                'verbose_name': '邮件通知',
                'verbose_name_plural': '邮件通知',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='email_notice_status_idx')],
            },
        ),
    ]
