# Generated by Django 5.2.1 on 2026-07-28 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_emailnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrequest',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='assets.inventoryitem', verbose_name='申请库存物品'),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='issued_inventory_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulfilled_requests', to='assets.inventorytransaction', verbose_name='库存发放流水'),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='needed_at',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='领用时间'),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='requested_item_type',
            field=models.CharField(choices=[('asset', '资产'), ('inventory', '库存物品')], db_index=True, default='asset', max_length=16, verbose_name='申请物品类型'),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='requested_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='申请数量'),
        ),
    ]
