# Generated by Django 5.2.1 on 2026-07-28 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0017_seed_administrative_expense_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='custodian_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.department', verbose_name='归属部门'),
        ),
    ]
