# Generated by Django 5.2.1 on 2026-07-29 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0018_alter_asset_custodian_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remote_path', models.CharField(max_length=512, unique=True, verbose_name='Nextcloud 路径')),
                ('original_name', models.CharField(max_length=255, verbose_name='原文件名')),
                ('content_type', models.CharField(blank=True, max_length=120, verbose_name='文件类型')),
                ('size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='文件大小')),
                ('sha256', models.CharField(db_index=True, max_length=64, verbose_name='SHA-256')),
                ('is_cover', models.BooleanField(default=False, verbose_name='封面')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='assets.asset', verbose_name='资产')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '资产图片',
                'verbose_name_plural': '资产图片',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remote_path', models.CharField(max_length=512, unique=True, verbose_name='Nextcloud 路径')),
                ('original_name', models.CharField(max_length=255, verbose_name='原文件名')),
                ('content_type', models.CharField(blank=True, max_length=120, verbose_name='文件类型')),
                ('size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='文件大小')),
                ('sha256', models.CharField(db_index=True, max_length=64, verbose_name='SHA-256')),
                ('document_type', models.CharField(choices=[('original', '合同原件'), ('signed', '盖章扫描件'), ('supplement', '补充协议'), ('quotation', '报价单'), ('other', '其他')], default='original', max_length=20, verbose_name='文件类别')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='assets.contract', verbose_name='合同')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '合同文件',
                'verbose_name_plural': '合同文件',
                'ordering': ['document_type', '-created_at'],
            },
        ),
    ]
