# Generated by Django 5.2.1 on 2026-07-29 08:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_contract_types(apps, schema_editor):
    ContractType = apps.get_model("assets", "ContractType")
    Contract = apps.get_model("assets", "Contract")
    rows = [
        ("PROCUREMENT", "采购合同"),
        ("SERVICE", "服务合同"),
        ("LEASE", "租赁合同"),
        ("ENGINEERING", "工程合同"),
        ("MAINTENANCE", "维保合同"),
        ("PROPERTY", "物业合同"),
        ("HR", "人力服务合同"),
        ("SOFTWARE", "软件与许可合同"),
        ("OTHER", "其他合同"),
    ]
    created = {}
    for code, name in rows:
        created[code], _ = ContractType.objects.get_or_create(code=code, defaults={"name": name})
    Contract.objects.filter(contract_type__isnull=True).update(contract_type=created["OTHER"])


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0019_assetimage_contractattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='合同类型')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='类型编码')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '合同类型',
                'verbose_name_plural': '合同类型',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='previous_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_contracts', to='assets.contract', verbose_name='上一期合同'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('active', '履行中'), ('expired', '已到期未处理'), ('completed', '已完成'), ('terminated', '已终止')], db_index=True, default='draft', max_length=16, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='ContractChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change_type', models.CharField(choices=[('extension', '延期续约'), ('supplement', '补充协议'), ('amount', '金额调整'), ('termination', '提前终止'), ('other', '其他变更')], max_length=20, verbose_name='变更类型')),
                ('changed_on', models.DateField(default=datetime.date.today, verbose_name='生效日期')),
                ('old_start_date', models.DateField(blank=True, null=True, verbose_name='原开始日期')),
                ('new_start_date', models.DateField(blank=True, null=True, verbose_name='新开始日期')),
                ('old_end_date', models.DateField(blank=True, null=True, verbose_name='原结束日期')),
                ('new_end_date', models.DateField(blank=True, null=True, verbose_name='新结束日期')),
                ('old_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='原合同金额')),
                ('new_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='新合同金额')),
                ('notes', models.TextField(verbose_name='变更说明')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='assets.contract', verbose_name='合同')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contract_changes', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
            ],
            options={
                'verbose_name': '合同变更记录',
                'verbose_name_plural': '合同变更记录',
                'ordering': ['-changed_on', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contractattachment',
            name='change',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='assets.contractchange', verbose_name='所属变更'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='assets.contracttype', verbose_name='合同类型'),
        ),
        migrations.RunPython(seed_contract_types, migrations.RunPython.noop),
    ]
