# Generated by Django 5.2.1 on 2026-08-06 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0022_category_wide_asset_number_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='supplement_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplement_contracts', to='assets.contract', verbose_name='母合同'),
        ),
    ]
