# Generated by Django 5.2.1 on 2026-08-06 08:12

from django.db import migrations, models


def merge_legacy_document_types(apps, schema_editor):
    ContractAttachment = apps.get_model("assets", "ContractAttachment")
    ContractAttachment.objects.filter(document_type="original").update(document_type="signed")
    ContractAttachment.objects.filter(
        document_type__in=["supplement", "quotation"],
    ).update(document_type="other")


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0023_contract_supplement_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractattachment',
            name='document_type',
            field=models.CharField(choices=[('signed', '盖章扫描件'), ('invoice', '发票'), ('other', '其他')], default='signed', max_length=20, verbose_name='文件类别'),
        ),
        migrations.RunPython(merge_legacy_document_types, migrations.RunPython.noop),
    ]
