# Generated by Django 5.2.1 on 2026-08-06 08:46

from django.db import migrations, models


def seed_module_toggles(apps, schema_editor):
    ModuleToggle = apps.get_model("assets", "ModuleToggle")
    modules = [
        ("assets", "资产台账"),
        ("inventory", "库存"),
        ("stocktake", "盘点"),
        ("vehicles", "车辆管理"),
        ("expenses", "费用台账"),
        ("procurement", "采购管理"),
        ("contracts", "合同管理"),
        ("reports", "报表"),
        ("settings", "设置"),
    ]
    ModuleToggle.objects.bulk_create(
        [ModuleToggle(code=code, label=label, is_enabled=True) for code, label in modules]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0024_alter_contractattachment_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleToggle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='模块编码')),
                ('label', models.CharField(max_length=64, verbose_name='模块名称')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '模块开关',
                'verbose_name_plural': '模块开关',
                'ordering': ['code'],
            },
        ),
        migrations.RunPython(seed_module_toggles, migrations.RunPython.noop),
    ]
