# Generated by Django 5.2.1 on 2026-08-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0025_moduletoggle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetevent',
            name='action',
            field=models.CharField(choices=[('created', '登记'), ('accepted', '验收入库'), ('assigned', '领用'), ('loaned', '借用'), ('extended', '延期'), ('returned', '归还'), ('transferred', '调拨'), ('repair_started', '送修'), ('repair_completed', '维修完成'), ('lost', '报失'), ('found', '找回'), ('retired', '退役'), ('disposed', '处置'), ('updated', '信息更新')], max_length=32, verbose_name='动作'),
        ),
    ]
