# Generated by Django 5.2.1 on 2026-08-20 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0027_link_asset_department_to_assignee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150, verbose_name='用户名快照')),
                ('display_name', models.CharField(max_length=150, verbose_name='姓名快照')),
                ('module', models.CharField(db_index=True, max_length=32, verbose_name='功能模块')),
                ('module_label', models.CharField(max_length=80, verbose_name='模块名称')),
                ('action', models.CharField(db_index=True, max_length=64, verbose_name='操作类型')),
                ('action_label', models.CharField(max_length=80, verbose_name='操作名称')),
                ('target_type', models.CharField(blank=True, max_length=80, verbose_name='对象类型')),
                ('target_id', models.CharField(blank=True, max_length=64, verbose_name='对象ID')),
                ('target_label', models.CharField(blank=True, max_length=255, verbose_name='操作对象')),
                ('method', models.CharField(max_length=8, verbose_name='请求方法')),
                ('path', models.CharField(max_length=500, verbose_name='请求路径')),
                ('status_code', models.PositiveSmallIntegerField(db_index=True, verbose_name='响应状态')),
                ('succeeded', models.BooleanField(db_index=True, verbose_name='操作成功')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='来源IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='客户端')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='附加信息')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['module', '-occurred_at'], name='op_log_module_time_idx'), models.Index(fields=['username', '-occurred_at'], name='op_log_user_time_idx')],
            },
        ),
    ]
