# Generated by Django 5.2.1 on 2026-08-20 03:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def enable_new_modules(apps, schema_editor):
    ModuleToggle = apps.get_model("assets", "ModuleToggle")
    AssetManagerRole = apps.get_model("assets", "AssetManagerRole")
    for code, label in [
        ("vehicles", "车辆管理"),
        ("suppliers", "供应商管理"),
        ("offices", "办事处管理"),
    ]:
        ModuleToggle.objects.update_or_create(
            code=code,
            defaults={"label": label, "is_enabled": True},
        )
    for role in AssetManagerRole.objects.all():
        scopes = list(role.scopes or [])
        if "procurement" in scopes and "suppliers" not in scopes:
            scopes.append("suppliers")
        if "contracts" in scopes and "offices" not in scopes:
            scopes.append("offices")
        if scopes != list(role.scopes or []):
            role.scopes = scopes
            role.save(update_fields=["scopes", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0028_operationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='办事处编码')),
                ('name', models.CharField(max_length=160, verbose_name='办事处名称')),
                ('status', models.CharField(choices=[('active', '使用中'), ('planned', '筹备中'), ('inactive', '暂停使用'), ('closed', '已关闭')], db_index=True, default='active', max_length=16, verbose_name='状态')),
                ('region', models.CharField(blank=True, max_length=80, verbose_name='所属区域')),
                ('city', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='城市')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='详细地址')),
                ('room_layout', models.CharField(blank=True, max_length=120, verbose_name='房型')),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='面积（平方米）')),
                ('sales_project', models.CharField(blank=True, max_length=255, verbose_name='销售项目归属')),
                ('cost_attribution', models.CharField(blank=True, max_length=255, verbose_name='费用归属明细')),
                ('landlord_name', models.CharField(blank=True, max_length=160, verbose_name='出租方')),
                ('landlord_phone', models.CharField(blank=True, max_length=80, verbose_name='出租方联系电话')),
                ('intermediary_name', models.CharField(blank=True, max_length=160, verbose_name='中介或机构')),
                ('intermediary_phone', models.CharField(blank=True, max_length=80, verbose_name='中介联系电话')),
                ('intermediary_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='中介费用')),
                ('intermediary_invoice_status', models.CharField(blank=True, max_length=120, verbose_name='中介费开票状态')),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='月租金')),
                ('rent_description', models.TextField(blank=True, verbose_name='租金说明')),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='押金')),
                ('deposit_status', models.CharField(blank=True, max_length=160, verbose_name='押金状态')),
                ('payment_frequency', models.CharField(blank=True, max_length=80, verbose_name='付款频率')),
                ('payment_method', models.CharField(blank=True, max_length=120, verbose_name='付款方式')),
                ('payment_terms', models.TextField(blank=True, verbose_name='付款要求')),
                ('latest_payment_period', models.CharField(blank=True, max_length=160, verbose_name='最近付款周期')),
                ('paid_period_start', models.DateField(blank=True, null=True, verbose_name='已付周期开始')),
                ('paid_period_end', models.DateField(blank=True, null=True, verbose_name='已付周期结束')),
                ('latest_payment_date', models.DateField(blank=True, null=True, verbose_name='最近付款日期')),
                ('next_payment_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='下次付款日期')),
                ('latest_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='最近付款金额')),
                ('responsible_name', models.CharField(blank=True, max_length=80, verbose_name='现场负责人')),
                ('responsible_phone', models.CharField(blank=True, max_length=80, verbose_name='负责人联系电话')),
                ('residents', models.TextField(blank=True, verbose_name='居住人员')),
                ('resident_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='居住人数')),
                ('renewal_status', models.TextField(blank=True, verbose_name='续租情况')),
                ('lease_summary', models.TextField(blank=True, verbose_name='历次租赁期限')),
                ('current_lease_period', models.CharField(blank=True, max_length=160, verbose_name='本期租赁期限')),
                ('lease_start', models.DateField(blank=True, null=True, verbose_name='本期开始日期')),
                ('lease_end', models.DateField(blank=True, db_index=True, null=True, verbose_name='合同约定到期日')),
                ('expected_move_out_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='预计退租日期')),
                ('feedback', models.TextField(blank=True, verbose_name='反馈事项')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='来源标识')),
            ],
            options={
                'verbose_name': '办事处',
                'verbose_name_plural': '办事处',
                'ordering': ['region', 'city', 'code'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='amount_description',
            field=models.TextField(blank=True, verbose_name='费用金额说明'),
        ),
        migrations.AddField(
            model_name='contract',
            name='cooperation_duration',
            field=models.CharField(blank=True, max_length=120, verbose_name='合作时长'),
        ),
        migrations.AddField(
            model_name='contract',
            name='cooperation_type',
            field=models.CharField(blank=True, max_length=120, verbose_name='合作类型'),
        ),
        migrations.AddField(
            model_name='contract',
            name='invoice_tax_rate',
            field=models.CharField(blank=True, max_length=80, verbose_name='开票税点'),
        ),
        migrations.AddField(
            model_name='contract',
            name='invoice_type',
            field=models.CharField(blank=True, max_length=80, verbose_name='开票类型'),
        ),
        migrations.AddField(
            model_name='contract',
            name='party_a',
            field=models.CharField(blank=True, max_length=180, verbose_name='签订甲方'),
        ),
        migrations.AddField(
            model_name='contract',
            name='party_a_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='甲方地址'),
        ),
        migrations.AddField(
            model_name='contract',
            name='party_a_contact',
            field=models.CharField(blank=True, max_length=160, verbose_name='甲方联系人'),
        ),
        migrations.AddField(
            model_name='contract',
            name='party_b_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='乙方地址'),
        ),
        migrations.AddField(
            model_name='contract',
            name='party_b_contact',
            field=models.CharField(blank=True, max_length=160, verbose_name='乙方联系人'),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment_method',
            field=models.CharField(blank=True, max_length=160, verbose_name='付款方式'),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment_terms',
            field=models.TextField(blank=True, verbose_name='付款要求'),
        ),
        migrations.AddField(
            model_name='contract',
            name='service_content',
            field=models.TextField(blank=True, verbose_name='服务项目内容'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='brand_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='品牌名称'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='business_license_status',
            field=models.CharField(choices=[('registered', '已登记'), ('missing', '未登记'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='营业执照状态'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='business_scope',
            field=models.TextField(blank=True, verbose_name='业务范围'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='category',
            field=models.CharField(blank=True, max_length=120, verbose_name='供应商类别'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='cooperation_started',
            field=models.CharField(blank=True, max_length=40, verbose_name='拓展时间'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='cooperation_status',
            field=models.CharField(blank=True, max_length=40, verbose_name='合作状态'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='evaluation',
            field=models.CharField(blank=True, max_length=40, verbose_name='合作评价'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=120, verbose_name='来源标识'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='asset_card_code',
            field=models.CharField(blank=True, max_length=80, verbose_name='资产卡片编码'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='asset_number',
            field=models.CharField(blank=True, max_length=80, verbose_name='资产编号'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='company',
            field=models.CharField(blank=True, max_length=120, verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='handler_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='经手人'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_started_at',
            field=models.DateField(blank=True, null=True, verbose_name='保险开始日期'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurer_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='保险公司'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='初次登记日期'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='supervisor_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='监管人'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='use_scope',
            field=models.CharField(blank=True, max_length=255, verbose_name='使用范围'),
        ),
        migrations.AddField(
            model_name='contract',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='assets.office', verbose_name='办事处'),
        ),
        migrations.CreateModel(
            name='SupplierAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remote_path', models.CharField(max_length=512, unique=True, verbose_name='Nextcloud 路径')),
                ('original_name', models.CharField(max_length=255, verbose_name='原文件名')),
                ('content_type', models.CharField(blank=True, max_length=120, verbose_name='文件类型')),
                ('size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='文件大小')),
                ('sha256', models.CharField(db_index=True, max_length=64, verbose_name='SHA-256')),
                ('document_type', models.CharField(choices=[('business_license', '营业执照'), ('qualification', '资质证照'), ('other', '其他')], default='business_license', max_length=24, verbose_name='文件类别')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='assets.supplier', verbose_name='供应商')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '供应商文件',
                'verbose_name_plural': '供应商文件',
                'ordering': ['document_type', '-created_at'],
            },
        ),
        migrations.RunPython(enable_new_modules, migrations.RunPython.noop),
    ]
