# Generated by Django 5.2.1 on 2026-09-02 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0030_office_resident_capacity_and_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='ldap_department_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='LDAP 部门 ID'),
        ),
        migrations.AddField(
            model_name='department',
            name='ldap_dn',
            field=models.CharField(blank=True, max_length=512, verbose_name='LDAP DN'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='ldap_dn',
            field=models.CharField(blank=True, max_length=512, verbose_name='LDAP DN'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='ldap_uid',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='LDAP UID'),
        ),
    ]
