<script setup lang="ts">
import { computed, onMounted, reactive, ref } from "vue";
import { api, ApiError } from "../api";
import type { Contract, ExpenseCategory, PurchaseLine, PurchaseOrder, PurchaseRequest, Supplier } from "../types";

const props=defineProps<{canManage:boolean}>(); type Tab="requests"|"orders";
const tab=ref<Tab>("requests"), requests=ref<PurchaseRequest[]>([]), orders=ref<PurchaseOrder[]>([]), suppliers=ref<Supplier[]>([]), contracts=ref<Contract[]>([]), categories=ref<ExpenseCategory[]>([]), error=ref("");
const showRequest=ref(false), showOrder=ref(false), selected=ref<PurchaseRequest|null>(null);
const requestForm=reactive<{needed_on:string;reason:string;category:string;items:PurchaseLine[]}>({needed_on:"",reason:"",category:"",items:[{name:"",specification:"",quantity:1,unit:"件",estimated_unit_price:""}]});
const orderForm=reactive<{request:string;supplier:string;contract:string;status:string;ordered_on:string;expected_on:string;kingdee_code:string;notes:string;items:PurchaseLine[]}>({request:"",supplier:"",contract:"",status:"draft",ordered_on:new Date().toISOString().slice(0,10),expected_on:"",kingdee_code:"",notes:"",items:[]});
const pending=computed(()=>requests.value.filter(x=>x.status==="pending").length);
function formatError(err:unknown,fallback:string){return err instanceof ApiError?Object.values(err.errors).flat().join(" ")||err.message:fallback}
async function load(){try{requests.value=await api<PurchaseRequest[]>("/purchase-requests/");categories.value=await api<ExpenseCategory[]>("/expense-categories/");if(props.canManage)[orders.value,suppliers.value,contracts.value]=await Promise.all([api<PurchaseOrder[]>("/purchase-orders/"),api<Supplier[]>("/suppliers/"),api<Contract[]>("/contracts/")]);}catch(err){error.value=formatError(err,"采购信息暂时无法加载。")}}
function addRequestLine(){requestForm.items.push({name:"",specification:"",quantity:1,unit:"件",estimated_unit_price:""})} function removeRequestLine(index:number){if(requestForm.items.length>1)requestForm.items.splice(index,1)}
async function createRequest(){try{await api("/purchase-requests/",{method:"POST",body:JSON.stringify({...requestForm,category:requestForm.category?Number(requestForm.category):null})});showRequest.value=false;Object.assign(requestForm,{needed_on:"",reason:"",category:"",items:[{name:"",specification:"",quantity:1,unit:"件",estimated_unit_price:""}]});await load()}catch(err){error.value=formatError(err,"采购申请未提交。")}}
async function decide(item:PurchaseRequest,action:"approve"|"reject"){try{await api(`/purchase-requests/${item.id}/${action}/`,{method:"POST",body:JSON.stringify({manager_notes:""})});await load()}catch(err){error.value=formatError(err,"审批状态未更新。")}}
function prepareOrder(item?:PurchaseRequest){selected.value=item||null;orderForm.request=item?String(item.id):"";orderForm.items=(item?.items||[{name:"",specification:"",quantity:1,unit:"件",estimated_unit_price:""}]).map(x=>({name:x.name,specification:x.specification,quantity:x.quantity,unit:x.unit,unit_price:x.estimated_unit_price||0}));showOrder.value=true}
async function createOrder(){try{await api("/purchase-orders/",{method:"POST",body:JSON.stringify({...orderForm,request:orderForm.request?Number(orderForm.request):null,supplier:Number(orderForm.supplier),contract:orderForm.contract?Number(orderForm.contract):null,expected_on:orderForm.expected_on||null})});showOrder.value=false;await load()}catch(err){error.value=formatError(err,"采购订单未保存。")}}
async function advanceOrder(item:PurchaseOrder){const next=item.status==='draft'?'ordered':item.status==='ordered'?'received':item.status==='partial'?'received':item.status==='received'?'closed':'';if(!next)return;try{await api(`/purchase-orders/${item.id}/`,{method:"PATCH",body:JSON.stringify({status:next,...(next==='received'?{received_on:new Date().toISOString().slice(0,10)}:{})})});await load()}catch(err){error.value=formatError(err,"订单状态未更新。")}}
function money(v:string|number){return `¥${Number(v).toLocaleString("zh-CN",{minimumFractionDigits:2})}`}
onMounted(load);
</script>
<template><div class="page module-page admin-module-page"><header class="page-intro"><div><p class="eyebrow">采购执行</p><h1>采购申请、下单与到货</h1></div><div class="page-actions"><button class="primary-button" @click="showRequest=true">提交采购申请</button></div></header><section class="admin-kpi-strip"><div><span>待审批申请</span><strong>{{pending}}</strong></div><div><span>采购申请</span><strong>{{requests.length}}</strong></div><div v-if="canManage"><span>执行中订单</span><strong>{{orders.filter(x=>!['closed','cancelled'].includes(x.status)).length}}</strong></div><div v-if="canManage"><span>可选供应商</span><strong>{{suppliers.filter(x=>x.is_active).length}}</strong></div></section><nav class="ledger-tabs"><button :class="{active:tab==='requests'}" @click="tab='requests'">采购申请</button><button v-if="canManage" :class="{active:tab==='orders'}" @click="tab='orders'">采购订单</button></nav><div v-if="error" class="error-block">{{error}}</div>
<section v-if="tab==='requests'" class="ledger-panel"><table class="admin-table"><thead><tr><th>申请单 / 申请人</th><th>采购用途</th><th>采购内容</th><th>期望到货</th><th>预计金额</th><th>状态</th><th></th></tr></thead><tbody><tr v-for="item in requests" :key="item.id"><td><strong>{{item.request_no}}</strong><small>{{item.requester_name}} · {{item.department_name||'未设置部门'}}</small></td><td>{{item.reason}}<small>{{item.category_name||'未设置费用类别'}}</small></td><td>{{item.items.map(x=>`${x.name} × ${x.quantity}`).join('；')}}</td><td>{{item.needed_on||'未指定'}}</td><td><strong>{{money(item.estimated_amount)}}</strong></td><td><span class="record-status" :data-status="item.status">{{item.status_label}}</span></td><td><div v-if="canManage&&item.status==='pending'" class="row-actions"><button class="text-button" @click="decide(item,'approve')">批准</button><button class="text-button danger" @click="decide(item,'reject')">驳回</button></div><button v-if="canManage&&item.status==='approved'" class="text-button" @click="prepareOrder(item)">生成订单</button></td></tr></tbody></table><div v-if="!requests.length" class="empty-state large">还没有采购申请。</div></section>
<section v-else class="ledger-panel"><div class="panel-actions"><button class="primary-button" @click="prepareOrder()">新建采购订单</button></div><table class="admin-table"><thead><tr><th>订单号</th><th>供应商</th><th>采购内容</th><th>下单 / 到货</th><th>金额</th><th>状态</th><th></th></tr></thead><tbody><tr v-for="item in orders" :key="item.id"><td><strong>{{item.order_no}}</strong><small>{{item.request_no||'直接采购'}}</small></td><td>{{item.supplier_name}}<small>{{item.contract_name}}</small></td><td>{{item.items.map(x=>`${x.name} × ${x.quantity}`).join('；')}}</td><td>{{item.ordered_on||'未下单'}}<small>{{item.expected_on?`预计 ${item.expected_on}`:'未设置到货日期'}}</small></td><td><strong>{{money(item.total_amount)}}</strong></td><td><span class="record-status" :data-status="item.status">{{item.status_label}}</span></td><td><button v-if="['draft','ordered','partial','received'].includes(item.status)" class="text-button" @click="advanceOrder(item)">{{item.status==='draft'?'确认下单':item.status==='received'?'关闭订单':'确认到货'}}</button></td></tr></tbody></table><div v-if="!orders.length" class="empty-state large">还没有采购订单。</div></section>
<div v-if="showRequest" class="modal-backdrop" @click.self="showRequest=false"><form class="modal-panel admin-form-modal" @submit.prevent="createRequest"><header><div><p class="eyebrow">采购申请</p><h2>说明需求与预计金额</h2></div><button type="button" class="icon-button" @click="showRequest=false">×</button></header><div class="form-grid"><label><span>期望到货日期</span><input v-model="requestForm.needed_on" type="date" /></label><label><span>费用类别</span><select v-model="requestForm.category"><option value="">未设置</option><option v-for="x in categories" :key="x.id" :value="x.id">{{x.name}}</option></select></label><label class="wide"><span>采购用途</span><textarea v-model="requestForm.reason" required></textarea></label></div><div class="line-editor"><header><strong>采购内容</strong><button type="button" class="text-button" @click="addRequestLine">添加一项</button></header><div v-for="(line,index) in requestForm.items" :key="index" class="purchase-line"><input v-model="line.name" required placeholder="物品或服务"/><input v-model="line.specification" placeholder="规格说明"/><input v-model="line.quantity" type="number" min="0.01" step="0.01" required placeholder="数量"/><input v-model="line.unit" required placeholder="单位"/><input v-model="line.estimated_unit_price" type="number" min="0" step="0.01" required placeholder="预计单价"/><button type="button" class="icon-button" @click="removeRequestLine(index)">×</button></div></div><button class="primary-button full">提交采购申请</button></form></div>
<div v-if="showOrder" class="modal-backdrop" @click.self="showOrder=false"><form class="modal-panel admin-form-modal" @submit.prevent="createOrder"><header><div><p class="eyebrow">采购订单</p><h2>{{selected?`承接 ${selected.request_no}`:'新建采购订单'}}</h2></div><button type="button" class="icon-button" @click="showOrder=false">×</button></header><div class="form-grid"><label><span>供应商</span><select v-model="orderForm.supplier" required><option value="">请选择</option><option v-for="x in suppliers.filter(x=>x.is_active)" :key="x.id" :value="x.id">{{x.name}}</option></select></label><label><span>关联合同</span><select v-model="orderForm.contract"><option value="">未设置</option><option v-for="x in contracts" :key="x.id" :value="x.id">{{x.contract_no}} · {{x.name}}</option></select></label><label><span>下单日期</span><input v-model="orderForm.ordered_on" type="date"/></label><label><span>预计到货</span><input v-model="orderForm.expected_on" type="date"/></label><label><span>金蝶编码</span><input v-model="orderForm.kingdee_code"/></label><label><span>状态</span><select v-model="orderForm.status"><option value="draft">草稿</option><option value="ordered">已下单</option></select></label></div><div class="line-editor"><header><strong>订单内容</strong></header><div v-for="(line,index) in orderForm.items" :key="index" class="purchase-line"><input v-model="line.name" required placeholder="物品或服务"/><input v-model="line.specification" placeholder="规格说明"/><input v-model="line.quantity" type="number" min="0.01" step="0.01" required/><input v-model="line.unit" required/><input v-model="line.unit_price" type="number" min="0" step="0.01" required placeholder="含税单价"/></div></div><label class="wide block-label"><span>备注</span><textarea v-model="orderForm.notes"></textarea></label><button class="primary-button full">保存采购订单</button></form></div></div></template>
